name: Token Branch Handler
on:
  push:
    branches:
      - main
      - release/v*

jobs:
  preparation:
    name: Collecting data
    runs-on: ubuntu-latest
    steps:
      - name: Get release branches
        id: release-branches
        run: echo "release-branches=$(git branch -r --list origin/main origin/release/v*)" >> $GITHUB_OUTPUT

      - name: output
        run: echo "Release branches ${{ steps.release-branches.outputs.release-branches }}"
